# Generated by Django 5.2 on 2025-04-29 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0010_auto_20250427_2224"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="phone_number",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
