services:
  - type: web
    name: djcrm
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn djcrm.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        fromDatabase:
          name: djcrm-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: djcrm-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: djcrm-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: djcrm-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: djcrm-db
          property: port
databases:
  - name: djcrm-db
    databaseName: djcrm
    user: djcrm_user
