--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
--SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: djcrmuser
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: leads_agent; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.leads_agent (
    id integer NOT NULL,
    user_id integer NOT NULL,
    organization_id integer NOT NULL
);


ALTER TABLE public.leads_agent OWNER TO postgres;

--
-- Name: leads_agent_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.leads_agent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_agent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leads_category; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.leads_category (
    id integer NOT NULL,
    name character varying(30) NOT NULL,
    organization_id integer NOT NULL
);


ALTER TABLE public.leads_category OWNER TO postgres;

--
-- Name: leads_category_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.leads_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leads_lead; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.leads_lead (
    id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    age integer NOT NULL,
    agent_id integer,
    organization_id integer NOT NULL,
    category_id integer,
    date_added timestamp with time zone NOT NULL,
    description text NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(10) NOT NULL
);


ALTER TABLE public.leads_lead OWNER TO postgres;

--
-- Name: leads_lead_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.leads_lead ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_lead_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leads_user; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.leads_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    is_agent boolean NOT NULL,
    is_organisor boolean NOT NULL
);


ALTER TABLE public.leads_user OWNER TO postgres;

--
-- Name: leads_user_groups; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.leads_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.leads_user_groups OWNER TO postgres;

--
-- Name: leads_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.leads_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leads_user_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.leads_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leads_user_user_permissions; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.leads_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.leads_user_user_permissions OWNER TO postgres;

--
-- Name: leads_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.leads_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leads_userprofile; Type: TABLE; Schema: public; Owner: djcrmuser
--

CREATE TABLE public.leads_userprofile (
    id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.leads_userprofile OWNER TO postgres;

--
-- Name: leads_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: djcrmuser
--

ALTER TABLE public.leads_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: leads_agent leads_agent_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_agent
    ADD CONSTRAINT leads_agent_pkey PRIMARY KEY (id);


--
-- Name: leads_agent leads_agent_user_id_key; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_agent
    ADD CONSTRAINT leads_agent_user_id_key UNIQUE (user_id);


--
-- Name: leads_category leads_category_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_category
    ADD CONSTRAINT leads_category_pkey PRIMARY KEY (id);


--
-- Name: leads_lead leads_lead_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_pkey PRIMARY KEY (id);


--
-- Name: leads_user_groups leads_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user_groups
    ADD CONSTRAINT leads_user_groups_pkey PRIMARY KEY (id);


--
-- Name: leads_user_groups leads_user_groups_user_id_group_id_88d9b26c_uniq; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user_groups
    ADD CONSTRAINT leads_user_groups_user_id_group_id_88d9b26c_uniq UNIQUE (user_id, group_id);


--
-- Name: leads_user leads_user_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user
    ADD CONSTRAINT leads_user_pkey PRIMARY KEY (id);


--
-- Name: leads_user_user_permissions leads_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user_user_permissions
    ADD CONSTRAINT leads_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: leads_user_user_permissions leads_user_user_permissions_user_id_permission_id_5b6424e2_uniq; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user_user_permissions
    ADD CONSTRAINT leads_user_user_permissions_user_id_permission_id_5b6424e2_uniq UNIQUE (user_id, permission_id);


--
-- Name: leads_user leads_user_username_key; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user
    ADD CONSTRAINT leads_user_username_key UNIQUE (username);


--
-- Name: leads_userprofile leads_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_userprofile
    ADD CONSTRAINT leads_userprofile_pkey PRIMARY KEY (id);


--
-- Name: leads_userprofile leads_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_userprofile
    ADD CONSTRAINT leads_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: leads_agent_oeganization_id_3ccb7f01; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_agent_oeganization_id_3ccb7f01 ON public.leads_agent USING btree (organization_id);


--
-- Name: leads_category_organization_id_eb5d8fa3; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_category_organization_id_eb5d8fa3 ON public.leads_category USING btree (organization_id);


--
-- Name: leads_lead_agent_id_fb1042af; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_lead_agent_id_fb1042af ON public.leads_lead USING btree (agent_id);


--
-- Name: leads_lead_category_id_eb5283fa; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_lead_category_id_eb5283fa ON public.leads_lead USING btree (category_id);


--
-- Name: leads_lead_organization_id_32e3ac83; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_lead_organization_id_32e3ac83 ON public.leads_lead USING btree (organization_id);


--
-- Name: leads_user_groups_group_id_17e877ad; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_user_groups_group_id_17e877ad ON public.leads_user_groups USING btree (group_id);


--
-- Name: leads_user_groups_user_id_6890bdd8; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_user_groups_user_id_6890bdd8 ON public.leads_user_groups USING btree (user_id);


--
-- Name: leads_user_user_permissions_permission_id_88335dba; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_user_user_permissions_permission_id_88335dba ON public.leads_user_user_permissions USING btree (permission_id);


--
-- Name: leads_user_user_permissions_user_id_2a9cf662; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_user_user_permissions_user_id_2a9cf662 ON public.leads_user_user_permissions USING btree (user_id);


--
-- Name: leads_user_username_e6a0880d_like; Type: INDEX; Schema: public; Owner: djcrmuser
--

CREATE INDEX leads_user_username_e6a0880d_like ON public.leads_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_leads_user_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_leads_user_id FOREIGN KEY (user_id) REFERENCES public.leads_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_agent leads_agent_organization_id_4b0daeda_fk_leads_userprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_agent
    ADD CONSTRAINT leads_agent_organization_id_4b0daeda_fk_leads_userprofile_id FOREIGN KEY (organization_id) REFERENCES public.leads_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_agent leads_agent_user_id_6baab848_fk_leads_user_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_agent
    ADD CONSTRAINT leads_agent_user_id_6baab848_fk_leads_user_id FOREIGN KEY (user_id) REFERENCES public.leads_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_category leads_category_organization_id_eb5d8fa3_fk_leads_userprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_category
    ADD CONSTRAINT leads_category_organization_id_eb5d8fa3_fk_leads_userprofile_id FOREIGN KEY (organization_id) REFERENCES public.leads_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_lead leads_lead_agent_id_fb1042af_fk_leads_agent_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_agent_id_fb1042af_fk_leads_agent_id FOREIGN KEY (agent_id) REFERENCES public.leads_agent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_lead leads_lead_category_id_eb5283fa_fk_leads_category_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_category_id_eb5283fa_fk_leads_category_id FOREIGN KEY (category_id) REFERENCES public.leads_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_lead leads_lead_organization_id_32e3ac83_fk_leads_userprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_organization_id_32e3ac83_fk_leads_userprofile_id FOREIGN KEY (organization_id) REFERENCES public.leads_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_user_groups leads_user_groups_group_id_17e877ad_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user_groups
    ADD CONSTRAINT leads_user_groups_group_id_17e877ad_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_user_groups leads_user_groups_user_id_6890bdd8_fk_leads_user_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user_groups
    ADD CONSTRAINT leads_user_groups_user_id_6890bdd8_fk_leads_user_id FOREIGN KEY (user_id) REFERENCES public.leads_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_user_user_permissions leads_user_user_perm_permission_id_88335dba_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user_user_permissions
    ADD CONSTRAINT leads_user_user_perm_permission_id_88335dba_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_user_user_permissions leads_user_user_permissions_user_id_2a9cf662_fk_leads_user_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_user_user_permissions
    ADD CONSTRAINT leads_user_user_permissions_user_id_2a9cf662_fk_leads_user_id FOREIGN KEY (user_id) REFERENCES public.leads_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_userprofile leads_userprofile_user_id_d30c092b_fk_leads_user_id; Type: FK CONSTRAINT; Schema: public; Owner: djcrmuser
--

ALTER TABLE ONLY public.leads_userprofile
    ADD CONSTRAINT leads_userprofile_user_id_d30c092b_fk_leads_user_id FOREIGN KEY (user_id) REFERENCES public.leads_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

