# Generated by Django 3.1.4 on 2025-04-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20250417_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='oeganization',
            new_name='organization',
        ),
    ]
